### ISSUE TITLE
Falta uma letra na função getChave

### ISSUE THREAD

**Issue by adevalter** [juancarlo99/read-xml-cte-nfe#1]
Opa 
Como está esta faltando uma lentra no final da função com isso retorna nulo
 public function getChave(): string
    {   

        if(isset($this->xml_objct_raiz->protnfe->infprot->**chnf)**){
            return trim( ( string ) $this->xml_objct_raiz->protnfe->infprot->chnfe );
        }

        return "";
      
    }

**Comment by juancarlo99** [comment]
Obrigado, foi feito a alteração.
